default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: naming_service_dev

test:
  <<: *default
  database: naming_service_test

production:
  <<: *default
  database: naming_service_prod
  username:
  password: